apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: test-ingress
 spec:
   backend:
     serviceName: customer-churn-service
     servicePort: 8500

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: test-ingress #hello-world-ing
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
# spec:
#   tls:
#   - secretName: tls-secret
#   rules:
#   - http:
#       paths:
#       - backend:
#           serviceName: customer-churn-service
#           servicePort: 8500
